### ISSUE TITLE
Falta código de ES_Newspapers.txt

### ISSUE THREAD

**Issue by philwebsurfer** [felipegonzalez/metodos-analiticos-2018#3]
Doctor,

Buenas tardes. Estaba revisando su código, específico de la sección [7.5](https://clever-mestorf-ee3f54.netlify.com/n-gramas-y-modelos-de-lenguaje.html#notas-de-periodico-modelo-de-n-gramas-simples.) y hace referencia a `datos/noticias/ES_Newspapers.txt` sin embargo no lo encuentro. Creo que sólo hizo falta subirlo al repo. :smile: 

Saludos cordiales,
Jorge Altamirano

**Comment by felipegonzalez** [comment]
Ya agregué la liga en docs. Los datos están aquí: [Es_Newspapers.txt](https://s3.amazonaws.com/es-noticias/Es_Newspapers.txt).

**Comment by philwebsurfer** [comment]
Gracias!
